### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by Lucas-Simon** [mdonoughe/neko-mac#1]
Hi, I want to try neko-mac but I don't know how to do it. Can you help me? ^^

**Comment by mdonoughe** [comment]
You can download the disk image from the [releases page](https://github.com/mdonoughe/neko-mac/releases). I haven't used Mac OS in years now so I don't know what extra steps you may need to do since this isn't from the app store, and I don't even know if it still works.

**Comment by nijisakai** [comment]
> You can download the disk image from the [releases page](https://github.com/mdonoughe/neko-mac/releases). I haven't used Mac OS in years now so I don't know what extra steps you may need to do since this isn't from the app store, and I don't even know if it still works.

It works smoothly on Big Sur. Thank you from cat lover
