### ISSUE TITLE
Application isn't notarized

### ISSUE THREAD

**Issue by MarkOtzen** [mdonoughe/neko-mac#4]
In modern versions of macOS, applications that aren't signed and notarised with a recognised Apple developer ID are deemed untrusted and require manual interaction from "Privacy and Security" in order to launch.
This application seems to be signed, but not notarised which means it won't run on off-the shelf installations. 
Since this is an operation that costs money, I understand that it isn't reasonable for what seems to be an abandoned project to implement in releases, but I thought I'd mention it anyways.

**Comment by mdonoughe** [comment]
I don't want to pay Apple a subscription to get rid of that for this app. If there were a free way like Fulcio, maybe, but I don't think Apple will ever allow something like that.
